services:
    junior-backend-test:
        container_name: fruitfy-contacts
        build:
            context: .
            dockerfile: ./devops/docker/Dockerfile
        ports:
            - "8000:80"
        volumes:
            - ./:/app
        environment:
            APP_ENV: local
        restart: unless-stopped
        networks:
            - fruitfy-network

networks:
    fruitfy-network:
        driver: bridge
